name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      checks: write # Add this line to grant write permission for checks
      contents: read
      actions: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Navigate to Next.js app directory
        working-directory: ./ranksterr-next-app
        run: |
          npm install

      - name: Run tests
        working-directory: ./ranksterr-next-app
        run: |
          npm run testJunit

      - name: Test Jest Junit Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: NextApp Jest Tests # Name of the check run which will be created
          path: "ranksterr-next-app/reports/jest/junit.xml" # Path to test results
          reporter: jest-junit # Format of test results
          fail-on-error: true
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Inject .env file from GitHub Secrets
      #   working-directory: ./ranksterr-next-app
      #   run: |
      #     echo "${{ secrets.NEXT_APP_ENV_FILE }}" > .env.production

      - name: Build the Next.js app
        working-directory: ./ranksterr-next-app
        run: npm run build

      - name: Delete next app off EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{secrets.EC2_HOST}}
          USER_NAME: ubuntu

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} <<EOF
            rm -rf /home/ubuntu/ranksterr-next/*
          EOF
          
      - name: Copy package.json files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ranksterr-next-app/package.json
          target: /home/ubuntu/ranksterr-next/

      # - name: Copy .env.production files to EC2
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     source: ranksterr-next-app/.env.production
      #     target: /home/ubuntu/ranksterr-next/
        
      - name: Copy .next files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ranksterr-next-app/.next
          target: /home/ubuntu/ranksterr-next/
          recursive: true

      - name: Copy public files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ranksterr-next-app/public
          target: /home/ubuntu/ranksterr-next/
          recursive: true


      - name: Trying Manually SSH and run script
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{secrets.EC2_HOST}}
          USER_NAME: ubuntu

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} <<EOF
            sudo systemctl restart ranksterr-next.service
            sudo systemctl reload nginx
          EOF
         
